import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,KEY,{auth:{persistSession:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info,x-supabase-api-version","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function user(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return null;const {data}=await db.auth.getUser(h.slice(7));return data.user||null}
async function token(uid:string){const {data,error}=await db.schema("private").from("deriv_oauth_credentials").select("access_token,refresh_token,expires_at,scopes").eq("user_id",uid).maybeSingle();if(error)throw error;if(!data?.access_token)throw new Error("DERIV_REAUTH_REQUIRED");const scopes=Array.isArray(data.scopes)?data.scopes.map(String):[];if(!scopes.includes("payment"))throw new Error("DERIV_PAYMENT_SCOPE_REQUIRED");if(data.expires_at&&Date.parse(data.expires_at)<=Date.now()){if(!data.refresh_token)throw new Error("DERIV_REAUTH_REQUIRED");throw new Error("DERIV_ACCESS_TOKEN_EXPIRED_RECONNECT_REQUIRED")}return data.access_token}
async function deriv(uid:string,path:string,opts:any={}){const t=await token(uid);const r=await fetch("https://api.derivws.com"+path,{...opts,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(opts.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.errors?.[0]?.message||body?.error||`DERIV_HTTP_${r.status}`);return body}
async function account(uid:string){const {data,error}=await db.from("real_trading_accounts").select("id,deriv_account_id,currency,balance,is_active,emergency_stopped").eq("user_id",uid).maybeSingle();if(error)throw error;if(!data?.deriv_account_id)throw new Error("REAL_DERIV_ACCOUNT_NOT_PROVISIONED");return data}
async function handle(uid:string,b:any){const op=String(b.operation||"wallets");if(op==="wallets"){const body=await deriv(uid,"/wallet/v1/wallets?conversion_currency="+encodeURIComponent(String(b.currency||"USD")));return {wallets:body?.data||[]}}if(op==="transactions"){const type=String(b.wallet_type||"main");return await deriv(uid,`/wallet/v1/transactions/${encodeURIComponent(type)}?per_page=100`)}if(op==="platform_transfer"){const a=await account(uid);const amount=Number(b.amount);const currency=String(b.currency||a.currency||"USD").toUpperCase();const direction=String(b.direction||"to_wallet");if(!["from_wallet","to_wallet"].includes(direction)||!(amount>0))throw new Error("INVALID_TRANSFER");const payload={amount:String(amount),currency,direction,request_id:String(b.request_id||crypto.randomUUID()),platform_account_id:String(a.deriv_account_id)};const body=await deriv(uid,"/wallet/v1/transfers/platforms",{method:"POST",body:JSON.stringify(payload)});await db.from("real_trading_audit").insert({account_id:a.id,user_id:uid,action:"REAL_WALLET_PLATFORM_TRANSFER",result:"SUCCESS",metadata:{direction,amount,currency,request_id:payload.request_id}});return body?.data||body}if(op==="validate_transfer"){const a=await account(uid);const payload={amount:String(b.amount),currency:String(b.currency||a.currency||"USD").toUpperCase(),direction:String(b.direction||"to_wallet"),request_id:String(b.request_id||crypto.randomUUID()),platform_account_id:String(a.deriv_account_id)};return await deriv(uid,"/wallet/v1/transfers/validate",{method:"POST",body:JSON.stringify(payload)})}if(op==="withdraw_verification"){const payload={agent_id:String(b.agent_id||""),amount:String(b.amount),currency:String(b.currency||"USD").toUpperCase()};if(!payload.agent_id)throw new Error("PAYMENT_AGENT_ID_REQUIRED");return await deriv(uid,"/payment-agents/v1/withdraw/verification_code",{method:"POST",body:JSON.stringify(payload)})}if(op==="withdraw"){const payload={agent_id:String(b.agent_id||""),amount:String(b.amount),currency:String(b.currency||"USD").toUpperCase(),verification_code:String(b.verification_code||""),request_id:String(b.request_id||crypto.randomUUID())};if(!payload.agent_id||!payload.verification_code)throw new Error("PAYMENT_AGENT_WITHDRAWAL_FIELDS_REQUIRED");return await deriv(uid,"/payment-agents/v1/withdraw",{method:"POST",body:JSON.stringify(payload)})}if(op==="withdraw_status"){const id=String(b.request_id||"");if(!id)throw new Error("REQUEST_ID_REQUIRED");return await deriv(uid,`/payment-agents/v1/withdraw/${encodeURIComponent(id)}`)}throw new Error("UNSUPPORTED_WALLET_OPERATION")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const u=await user(req);if(!u)return json({ok:false,error:"Authentication required"},401);try{return json({ok:true,data:await handle(u.id,await req.json().catch(()=>({})))})}catch(e){return json({ok:false,error:e instanceof Error?e.message:"WALLET_REQUEST_FAILED"},400)}});