import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(url,serviceKey,{auth:{persistSession:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-mt5-bridge-token","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const bearer=(r:Request)=>String(r.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();
async function userFromRequest(r:Request){const t=bearer(r);if(!t)return null;const c=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")||"",{global:{headers:{Authorization:"Bearer "+t}},auth:{persistSession:false}});const {data}=await c.auth.getUser();return data.user||null}
function bridgeAuthorized(r:Request){const configured=Deno.env.get("MT5_BRIDGE_TOKEN"),supplied=String(r.headers.get("x-mt5-bridge-token")||"").trim();return !!configured&&!!supplied&&supplied===configured}
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const path=new URL(req.url).pathname.replace(/\/+$/,"");try{
if(req.method==="GET"&&path.endsWith("/status")){const user=await userFromRequest(req);if(!user)return json({ok:false,error:"Authentication required"},401);const {data,error}=await db.from("mt5_connections").select("id,broker,server,login,environment,status,last_heartbeat_at,metadata,updated_at").eq("user_id",user.id).order("last_heartbeat_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;const hb=data?.last_heartbeat_at?Date.parse(data.last_heartbeat_at):0;const connected=!!data&&data.status==="connected"&&hb>Date.now()-45000;return json({ok:true,status:connected?"connected":data?"stale":"not_connected",connection:data?{...data,status:connected?"connected":"stale"}:null});}
if(req.method==="GET"&&path.endsWith("/health")){const {data,error}=await db.from("mt5_connections").select("status,last_heartbeat_at").order("last_heartbeat_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;const hb=data?.last_heartbeat_at?Date.parse(data.last_heartbeat_at):0;return json({ok:true,status:data&&data.status==="connected"&&hb>Date.now()-45000?"connected":data?"stale":"not_connected",last_heartbeat_at:data?.last_heartbeat_at||null});}

if(!bridgeAuthorized(req))return json({ok:false,error:"Bridge authentication required"},401);
if(req.method==="POST"&&path.endsWith("/heartbeat")){const user=await userFromRequest(req);if(!user)return json({ok:false,error:"Authentication required"},401);const b=await req.json();const userId=String(b.user_id||"").trim(),server=String(b.server||"").trim(),login=String(b.login||"").trim();if(!userId||!server||!login)return json({ok:false,error:"user_id, server and login are required"},400);if(userId!==user.id)return json({ok:false,error:"user_id does not match authenticated user"},403);const now=new Date().toISOString();const snapshot={terminal_connected:b.terminal_connected!==false,balance:num(b.balance),equity:num(b.equity),margin:num(b.margin),free_margin:num(b.free_margin),margin_level:num(b.margin_level),positions:Array.isArray(b.positions)?b.positions:[],received_at:now};const {data:connection,error}=await db.from("mt5_connections").upsert({user_id:userId,broker:String(b.broker||"Deriv"),server,login,account_currency:String(b.account_currency||"USD"),environment:"demo",status:snapshot.terminal_connected?"connected":"degraded",last_heartbeat_at:now,metadata:snapshot,updated_at:now},{onConflict:"user_id,server,login"}).select().single();if(error)throw error;const hb=await db.from("mt5_heartbeats").insert({user_id:userId,connection_id:connection.id,heartbeat_at:now,latency_ms:Number.isFinite(Number(b.latency_ms))?Number(b.latency_ms):null,terminal_connected:snapshot.terminal_connected,metadata:snapshot});if(hb.error)throw hb.error;const ev=await db.from("integration_events").insert({user_id:userId,integration:"mt5",event_type:"heartbeat",external_id:login,status:"received",payload:snapshot});if(ev.error)throw ev.error;return json({ok:true,status:"connected",connection_id:connection.id,heartbeat_at:now});}
if(req.method==="GET"&&path.endsWith("/snapshot")){const user=await userFromRequest(req);if(!user)return json({ok:false,error:"Authentication required"},401);const {data,error}=await db.from("mt5_connections").select("id,user_id,broker,server,login,account_currency,environment,status,last_heartbeat_at,metadata,updated_at").eq("user_id",user.id).order("last_heartbeat_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return json({ok:true,snapshot:data});}
return json({ok:false,error:"Route not found"},404);}catch(e){console.error("mt5-bridge failed",e instanceof Error?e.message:"unknown");return json({ok:false,error:"MT5 bridge request failed"},500)}});