import React,{useEffect,useState} from "react";
import {supabase} from "../supabaseClient";
import Sidebar from "../components/Sidebar";

const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function derive(orders=[]){
  const sorted=[...orders].sort((a,b)=>new Date(a.closed_at||a.created_at)-new Date(b.closed_at||b.created_at));
  let gp=0,gl=0,w=0,l=0,running=0,peak=0,maxDD=0,maxDDPct=0; const days=new Map();
  for(const o of sorted){const pnl=Number(o.realized_pnl||0);running+=pnl;peak=Math.max(peak,running);const dd=Math.max(0,peak-running);const pct=peak>0?dd/peak*100:0;maxDD=Math.max(maxDD,dd);maxDDPct=Math.max(maxDDPct,pct);if(pnl>0){gp+=pnl;w++}else if(pnl<0){gl+=Math.abs(pnl);l++}const date=new Date(o.closed_at||o.created_at).toISOString().slice(0,10);const d=days.get(date)||{date,pnl:0,dd:0,trades:0};d.pnl+=pnl;d.dd=Math.max(d.dd,dd);d.trades++;days.set(date,d)}
  const total=w+l;return{total,w,l,gp,gl,winRate:total?w/total*100:0,pf:gl?gp/gl:gp?99.99:0,avgW:w?gp/w:0,avgL:l?gl/l:0,maxDD,maxDDPct,days:[...days.values()].reverse()};
}
export default function AnalyticsOverviewLive(){
 const [open,setOpen]=useState(false),[tab,setTab]=useState("SANDBOX"),[data,setData]=useState(derive()),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let stop=false;(async()=>{setLoading(true);setError("");const table=tab==="SANDBOX"?"sandbox_orders":"real_orders";const q=await supabase.from(table).select("realized_pnl,closed_at,created_at,status").eq("status","CLOSED").order("closed_at",{ascending:true});if(stop)return;if(q.error){setError(q.error.message);setData(derive())}else setData(derive(q.data||[]));setLoading(false)})();return()=>{stop=true}},[tab]);
 const insights=data.total?[data.winRate>=50?"Closed-trade win rate is at or above 50% for the selected account.":"Closed-trade win rate is below 50%; review the trade distribution.",data.pf>1?"Gross profits exceed gross losses in the selected closed-trade set.":"Gross losses meet or exceed gross profits in the selected closed-trade set.",data.maxDDPct>0?"A non-zero peak-to-trough drawdown is present in the derived equity curve.":"No peak-to-trough drawdown is present in the available closed-trade sequence.","The intelligence layer is read-only and has no order execution capability."]:["No closed trades are available; performance conclusions are withheld."];
 return <div style={s.layout}><Sidebar isOpen={open} onClose={()=>setOpen(false)}/><main style={s.main}><header style={s.header}><button style={s.menu} onClick={()=>setOpen(true)}>☰</button><b style={s.brand}>VELTRION ANALYTICS INTELLIGENCE</b><div style={s.tabs}>{["SANDBOX","REAL"].map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?s.active:s.tab}>{x==="REAL"?"REAL DERIV":x}</button>)}</div></header><section style={s.content}>{loading&&<p style={s.muted}>Loading derived analytics…</p>}{error&&<p style={s.error}>{error}</p>}<div style={s.grid}><C l={"TOTAL P/L ("+tab+")"} v={money(data.gp-data.gl)}/><C l="WIN RATE" v={data.winRate.toFixed(2)+"%"}/><C l="PROFIT FACTOR" v={data.pf.toFixed(2)}/><C l="MAX DRAWDOWN" v={money(data.maxDD)+" ("+data.maxDDPct.toFixed(2)+"%)"}/></div><div style={s.card}><h3>Trade distribution</h3><p style={s.muted}>{data.total} closed trades · {data.w} wins · {data.l} losses · average win {money(data.avgW)} · average loss {money(data.avgL)}</p></div><div style={s.card}><h3>VELTRION AI INSIGHTS ENGINE</h3><ul style={s.list}>{insights.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div style={s.card}><h3>Daily performance & drawdown</h3>{data.days.length?data.days.map(d=><div key={d.date} style={s.row}><span>{d.date}</span><span>P/L {money(d.pnl)}</span><span>DD {money(d.dd)}</span></div>):<p style={s.muted}>No daily closed-trade data.</p>}</div></section></main></div>
}
function C({l,v}){return <div style={s.card}><small style={s.label}>{l}</small><strong style={s.value}>{v}</strong></div>}
const s={layout:{display:"flex",minHeight:"100vh",background:"transparent"},main:{flex:1,minWidth:0},header:{display:"flex",alignItems:"center",gap:16,padding:"15px 20px",borderBottom:"1px solid #30363d",background:"#161b22",flexWrap:"wrap"},menu:{background:"none",border:0,color:"inherit",fontSize:20},brand:{flex:1,letterSpacing:1},tabs:{display:"flex",border:"1px solid #30363d",borderRadius:6,overflow:"hidden"},tab:{background:"transparent",border:0,color:"#8b949e",padding:"7px 12px",fontWeight:700,fontSize:11},active:{background:"#238636",border:0,color:"#fff",padding:"7px 12px",fontWeight:700,fontSize:11},content:{padding:20,maxWidth:1100,margin:"0 auto"},grid:{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:15},card:{background:"#161b22",border:"1px solid #30363d",borderRadius:8,padding:18,marginBottom:15},label:{display:"block",color:"#8b949e",fontWeight:800},value:{display:"block",fontSize:24,marginTop:8},muted:{color:"#8b949e"},list:{color:"#8b949e",lineHeight:1.7},row:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",padding:"9px 0",borderBottom:"1px solid #30363d"},error:{color:"#f85149"}};
