import {useEffect,useState} from "react";
import Sidebar from "../components/Sidebar";
import {supabase} from "../supabaseClient";
const money=(v,c="USD")=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:c});
async function walletRequest(body){const {data,error}=await supabase.functions.invoke("wallet-service",{body});if(error)throw new Error(data?.error||error.message||"WALLET_REQUEST_FAILED");if(!data?.ok)throw new Error(data?.error||"WALLET_REQUEST_FAILED");return data.data}
export default function ProfitWalletView(){
 const [sidebarOpen,setSidebarOpen]=useState(false),[wallet,setWallet]=useState(null),[withdrawals,setWithdrawals]=useState([]),[derivWallets,setDerivWallets]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[amount,setAmount]=useState(""),[destination,setDestination]=useState(""),[agentId,setAgentId]=useState(""),[verificationCode,setVerificationCode]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){setError("AUTH_REQUIRED");return}const {data:account}=await supabase.from("real_trading_accounts").select("id,currency").eq("user_id",user.id).maybeSingle();if(!account){setWallet(null);return}const {data:w}=await supabase.from("real_profit_wallets").select("id,available_balance,reserved_balance,currency,updated_at").eq("account_id",account.id).maybeSingle();setWallet(w||null);if(w){const {data:rows}=await supabase.from("withdrawals").select("id,amount,status,destination_type,provider_reference,requested_at,completed_at").eq("wallet_id",w.id).order("requested_at",{ascending:false}).limit(20);setWithdrawals(rows||[])}try{const d=await walletRequest({operation:"wallets",currency:account.currency||"USD"});setDerivWallets(d?.wallets||[])}catch(e){setError(e.message||"DERIV_WALLET_LOAD_FAILED")}}
 useEffect(()=>{load()},[]);
 const available=Number(wallet?.available_balance||0),reserved=Number(wallet?.reserved_balance||0),withdrawable=Math.max(0,available-reserved);
 async function requestInternal(){setBusy(true);setError("");setMessage("");try{const value=Number(amount);if(!wallet||!Number.isFinite(value)||value<=0||value>withdrawable||!destination.trim())throw new Error("INVALID_WITHDRAWAL_REQUEST");const {error:e}=await supabase.rpc("request_profit_withdrawal",{p_wallet_id:wallet.id,p_amount:value,p_destination:destination.trim()});if(e)throw e;setAmount("");setDestination("");setMessage("Internal withdrawal request reserved.");await load()}catch(e){setError(e?.message||"WITHDRAWAL_REQUEST_FAILED")}finally{setBusy(false)}}
 async function requestCode(){setBusy(true);setError("");setMessage("");try{await walletRequest({operation:"withdraw_verification",agent_id:agentId,amount, currency:wallet?.currency||"USD"});setMessage("Deriv verification code requested. Check the contact method registered with Deriv.");}catch(e){setError(e.message||"DERIV_VERIFICATION_FAILED")}finally{setBusy(false)}}
 async function withdrawDeriv(){setBusy(true);setError("");setMessage("");try{const value=Number(amount);if(!(value>0)||!agentId||!verificationCode)throw new Error("DERIV_WITHDRAWAL_FIELDS_REQUIRED");const r=await walletRequest({operation:"withdraw",agent_id:agentId,amount:value,currency:wallet?.currency||"USD",verification_code:verificationCode,request_id:crypto.randomUUID()});setMessage("Deriv withdrawal submitted: "+String(r?.data?.status||r?.status||"pending"));setVerificationCode("");await load()}catch(e){setError(e.message||"DERIV_WITHDRAWAL_FAILED")}finally{setBusy(false)}}
 return <div className="app-layout"><Sidebar isOpen={sidebarOpen} onClose={()=>setSidebarOpen(false)}/><div className="app-main"><header className="topbar"><button className="menu-button" onClick={()=>setSidebarOpen(true)}>☰</button><span className="topbar-brand">VELTRION PROFIT WALLET</span><span className="admin-badge">● REAL MONEY</span></header><main className="content"><div className="page-heading"><div><span className="eyebrow">REAL MONEY CENTER</span><h1>Profit Wallet</h1><p>Internal reconciled profit is kept separate from Deriv's actual wallet. Deriv wallet transfers use the payment-scoped API.</p></div></div>
 <div className="metric-grid"><div className="metric-card"><small>REAL PROFIT AVAILABLE</small><strong>{money(available,wallet?.currency)}</strong><span>Reconciled internal profit</span></div><div className="metric-card"><small>RESERVED</small><strong>{money(reserved,wallet?.currency)}</strong><span>Pending internal requests</span></div><div className="metric-card"><small>DERIV WALLETS</small><strong>{derivWallets.length}</strong><span>Authenticated wallet records</span></div><div className="metric-card"><small>SANDBOX</small><strong>$0.00</strong><span>Virtual funds cannot become cash</span></div></div>
 {error&&<div className="error-panel">{error}</div>}{message&&<div className="vt-success">{message}</div>}
 <section className="panel"><div className="panel-title">DERIV WALLET BALANCES</div>{derivWallets.length?derivWallets.map(w=><div className="audit-row" key={w.wallet_id||w.type}><span>{w.type||"wallet"}</span><b>{w.balances?.[wallet?.currency||"USD"]?.balance??w.balance??"—"} {wallet?.currency||"USD"}</b></div>):<div className="empty">No Deriv wallet data is currently available. Reconnect OAuth with payment scope if required.</div>}</section>
 <section className="panel"><div className="panel-title">INTERNAL PROFIT WITHDRAWAL REQUEST</div>{wallet?<><div className="real-grid"><label>Amount ({wallet.currency})<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" max={withdrawable}/></label><label>Authorized destination reference<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Internal settlement destination"/></label></div><button className="button primary full" onClick={requestInternal} disabled={busy||withdrawable<=0}>{busy?"PROCESSING…":"RESERVE INTERNAL WITHDRAWAL"}</button></>:<div className="empty">Real profit wallet has not yet been provisioned by a successful live reconciliation.</div>}</section>
 <section className="panel"><div className="panel-title">DERIV PAYMENT-AGENT WITHDRAWAL</div><p>Deriv's current API withdrawal rail is payment-agent based and requires the payment OAuth scope plus a one-time verification code. The app never stores the code.</p><div className="real-grid"><label>Payment-agent ID<input value={agentId} onChange={e=>setAgentId(e.target.value)} placeholder="Agent ID"/></label><label>Withdrawal amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01"/></label><label>Verification code<input value={verificationCode} onChange={e=>setVerificationCode(e.target.value)} inputMode="numeric" maxLength="6" placeholder="6 digits"/></label></div><div className="real-actions"><button className="button" onClick={requestCode} disabled={busy||!agentId||!amount}>REQUEST VERIFICATION CODE</button><button className="button danger" onClick={withdrawDeriv} disabled={busy||!agentId||!amount||!verificationCode}>SUBMIT DERIV WITHDRAWAL</button></div></section>
 <section className="panel"><div className="panel-title">WITHDRAWAL HISTORY</div>{withdrawals.length?withdrawals.map(w=><div className="audit-row" key={w.id}><span>{money(w.amount,wallet?.currency)} · {w.destination_type||"AUTHORIZED ROUTE"}</span><span>{String(w.status).toUpperCase()} · {new Date(w.requested_at).toLocaleString()}</span></div>):<div className="empty">No internal withdrawal records.</div>}</section>
 </main></div></div>
}