import { useEffect, useMemo, useRef, useState } from "react";
import Sidebar from "../components/Sidebar";
import LiveMarketPanel from "../components/LiveMarketPanel";
import { supabase } from "../supabaseClient";

const fn = "trading-service";
const walletFn = "wallet-service";
const TIMEFRAMES = [
  {label:"1m",seconds:60},{label:"5m",seconds:300},{label:"15m",seconds:900},
  {label:"1h",seconds:3600},{label:"4h",seconds:14400},{label:"1d",seconds:86400}
];
const fmt=(n,d=5)=>Number.isFinite(Number(n))?Number(n).toLocaleString("en-US",{maximumFractionDigits:d}):"—";
async function invoke(name, body){
  const {data,error}=await supabase.functions.invoke(name,{body});
  if(error) throw new Error(data?.error||error.message||"REQUEST_FAILED");
  if(!data?.ok) throw new Error(data?.error||"REQUEST_FAILED");
  return data.data;
}
function Chart({candles,price,symbol}){
  const data=candles.slice(-100),w=1100,h=360,p=18;
  if(!data.length)return <div className="vt-chart-empty"><span className="vt-live-dot"/> Loading {symbol} candles…</div>;
  const lo=Math.min(...data.map(x=>x.low),Number(price)||Infinity),hi=Math.max(...data.map(x=>x.high),Number(price)||-Infinity),range=hi-lo||1,step=(w-90)/data.length,y=v=>p+(hi-v)/range*(h-45);
  return <svg className="vt-chart-svg" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Live chart for ${symbol}`}>
    {[0,1,2,3,4].map(i=><line key={i} x1={p} x2={w-72} y1={p+(h-45)*i/4} y2={p+(h-45)*i/4} stroke="currentColor" opacity=".12" strokeDasharray="3 5"/>)}
    {data.map((c,i)=>{const x=p+i*step+step/2,up=c.close>=c.open,col=up?"#34d399":"#f87171",bw=Math.max(2,Math.min(10,step*.62));return <g key={c.time}><line x1={x} x2={x} y1={y(c.high)} y2={y(c.low)} stroke={col}/><rect x={x-bw/2} y={y(Math.max(c.open,c.close))} width={bw} height={Math.max(1,Math.abs(y(c.open)-y(c.close)))} fill={col}/></g>})}
    {Number.isFinite(Number(price))&&<><line x1={p} x2={w-72} y1={y(Number(price))} y2={y(Number(price))} stroke="#60a5fa" strokeDasharray="5 4"/><text x={w-65} y={y(Number(price))+4} fill="#93c5fd" fontSize="11">{fmt(price,8)}</text></>}
  </svg>;
}
export default function RealMT5Terminal(){
 const [side,setSide]=useState(false),[symbol,setSymbol]=useState("1HZ100V"),[price,setPrice]=useState(null),[feed,setFeed]=useState("WAITING");
 const [candles,setCandles]=useState([]),[ticks,setTicks]=useState([]),[tf,setTf]=useState(300),[account,setAccount]=useState(null),[portfolio,setPortfolio]=useState([]);
 const marketSocketRef=useRef(null);
 const [stake,setStake]=useState("10"),[growth,setGrowth]=useState("1"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 const [selectedContract,setSelectedContract]=useState(null),[wallets,setWallets]=useState([]),[transferAmount,setTransferAmount]=useState(""),[transferDir,setTransferDir]=useState("to_wallet"),[transferBusy,setTransferBusy]=useState(false);
 const refresh=async()=>{try{const s=await invoke(fn,{operation:"real_snapshot"});setAccount(s||null);setPortfolio(s?.portfolio?.contracts||[]);}catch(e){setError(e.message||"REAL_ACCOUNT_SYNC_FAILED")}};
 useEffect(()=>{refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);
 useEffect(()=>{let dead=false,retry;setCandles([]);setTicks([]);setPrice(null);setFeed("CONNECTING");const connect=()=>{if(dead)return;const ws=new WebSocket("wss://ws.binaryws.com/websockets/v3?app_id=1089");marketSocketRef.current=ws;ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:symbol,adjust_start_time:1,count:180,end:"latest",style:"candles",granularity:tf,subscribe:1,req_id:7001}));ws.send(JSON.stringify({ticks:symbol,subscribe:1,req_id:7002}));};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.error)return;if(m.msg_type==="history"||m.msg_type==="candles"){const raw=m.candles||[];if(raw.length)setCandles(raw.map(c=>({time:Number(c.epoch),open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close)})).filter(c=>[c.time,c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time).slice(-180));}if(m.msg_type==="tick"&&m.tick){const q=Number(m.tick.quote),epoch=Number(m.tick.epoch);if(!Number.isFinite(q)||!Number.isFinite(epoch))return;setPrice(q);setFeed("LIVE");setTicks(a=>[{quote:q,epoch},...a].slice(0,40));setCandles(a=>{const bucket=Math.floor(epoch/tf)*tf,last=a[a.length-1];if(!last||last.time!==bucket)return [...a,{time:bucket,open:q,high:q,low:q,close:q}].slice(-180);return [...a.slice(0,-1),{...last,high:Math.max(last.high,q),low:Math.min(last.low,q),close:q}];});}}catch{setError("LIVE_MARKET_DATA_PARSE_FAILED")}};ws.onclose=()=>{if(!dead)retry=setTimeout(connect,2500)};ws.onerror=()=>{setFeed("RECONNECTING")};};connect();return()=>{dead=true;clearTimeout(retry);try{marketSocketRef.current?.close()}catch{}marketSocketRef.current=null}},[symbol,tf]);
 const onTick=t=>{const q=Number(t?.quote);if(!Number.isFinite(q))return;setPrice(q);setFeed("LIVE");const bucket=Math.floor(Number(t.epoch)/tf)*tf;setCandles(a=>{const last=a[a.length-1];if(!last||last.time!==bucket)return [...a,{time:bucket,open:q,high:q,low:q,close:q}].slice(-180);return [...a.slice(0,-1),{...last,high:Math.max(last.high,q),low:Math.min(last.low,q),close:q}]})};
 const buy=async()=>{if(busy)return;setError("");setMsg("");if(!price)return setError("LIVE_PRICE_NOT_AVAILABLE");if(!account)return setError("REAL_ACCOUNT_NOT_SYNCHRONIZED");setBusy(true);try{const amount=Number(stake),gr=Number(growth);if(!(amount>0)||!(gr>0))throw new Error("INVALID_ORDER_PARAMETERS");const p=await invoke(fn,{operation:"accu_proposal",contract_template:{amount,basis:"stake",contract_type:"ACCU",currency:account?.currency||"USD",growth_rate:gr,underlying_symbol:symbol,duration:5,duration_unit:"m"}});const proposal=p?.proposal||p;const id=String(proposal?.id||"");const max=Number(proposal?.ask_price||proposal?.display_value||proposal?.price);if(!id||!(max>0))throw new Error("INVALID_PROPOSAL");const ok=window.confirm(`CONFIRM REAL ACCU BUY
${symbol} · ${amount} ${account?.currency||"USD"} · growth ${gr}%
This can place a real-money order if the server safety gate is released.`);if(!ok)return;const r=await invoke(fn,{operation:"buy",proposal_id:id,price:max,stake:amount,symbol,client_order_id:crypto.randomUUID()});setMsg(`REAL BUY CONFIRMED · contract ${r?.buy?.contract_id||r?.order?.deriv_contract_id||"created"}`);await refresh()}catch(e){setError(e.message||"REAL_BUY_FAILED")}finally{setBusy(false)}};
 const sell=async()=>{if(!selectedContract||busy)return;const id=String(selectedContract.contract_id||selectedContract.id||"");if(!id)return setError("CONTRACT_ID_REQUIRED");if(!window.confirm(`SELL REAL CONTRACT ${id} at market price?
Deriv will execute this as a real-money sell if the safety gate is released.`))return;setBusy(true);try{const r=await invoke(fn,{operation:"sell",contract_id:id,price:0});setMsg(`REAL SELL CONFIRMED · ${r?.sell?.contract_id||id}`);setSelectedContract(null);await refresh()}catch(e){setError(e.message||"REAL_SELL_FAILED")}finally{setBusy(false)}};
 const loadWallets=async()=>{try{const w=await invoke(walletFn,{operation:"wallets"});setWallets(w?.wallets||[])}catch(e){setError(e.message||"WALLET_LOAD_FAILED")}};
 const transfer=async()=>{if(transferBusy)return;const amount=Number(transferAmount);if(!(amount>0))return setError("INVALID_TRANSFER_AMOUNT");if(!window.confirm(`${transferDir==="from_wallet"?"FUND REAL TRADING ACCOUNT":"MOVE REAL FUNDS TO DERIV WALLET"}: ${amount} ${account?.currency||"USD"}?
This moves actual Deriv funds.`))return;setTransferBusy(true);try{const r=await invoke(walletFn,{operation:"platform_transfer",amount,currency:account?.currency||"USD",direction:transferDir,request_id:crypto.randomUUID()});setMsg(`REAL TRANSFER ACCEPTED · ${r?.request_id||""}`);setTransferAmount("");await loadWallets();await refresh()}catch(e){setError(e.message||"REAL_TRANSFER_FAILED")}finally{setTransferBusy(false)}};
 useEffect(()=>{loadWallets()},[]);
 const balance=Number(account?.balance?.balance ?? account?.balance ?? 0),eq=Number(account?.balance?.equity ?? account?.equity ?? balance);
 return <div className="app-layout"><Sidebar isOpen={side} onClose={()=>setSide(false)}/><div className="app-main"><header className="topbar"><button className="menu-button" onClick={()=>setSide(true)}>☰</button><span className="topbar-brand">VELTRION REAL TRADING WORKSTATION</span><span className="admin-badge real-badge">● DERIV REAL</span></header><main className="content vt-page">
 <header className="vt-heading"><div><span className="eyebrow real-eyebrow">MT5-STYLE / DERIV LIVE</span><h1>Professional Trading Terminal</h1><p>Full active-market watch, live chart, real account, positions, buy/sell execution and wallet transfer controls.</p></div><div className="vt-header-actions"><span className={feed==="LIVE"?"vt-feed live":"vt-feed"}><i/> {feed==="LIVE"?"LIVE MARKET DATA":feed}</span></div></header>
 <div className="market-account-strip"><div className="market-account-card"><span>REAL BALANCE</span><strong>{account?.currency||"USD"} {fmt(balance,2)}</strong><small>{account?.loginid||account?.login||"Real account"}</small></div><div className="market-account-card"><span>EQUITY</span><strong>{account?.currency||"USD"} {fmt(eq,2)}</strong><small>Server-reconciled</small></div><div className="market-account-card market-account-state"><span>EXECUTION STATE</span><strong>{portfolio.length} OPEN</strong><small>Server safety gate applies to every order</small></div></div>
 <LiveMarketPanel selectedSymbol={symbol} onSymbolChange={setSymbol} onPriceChange={onTick}/>
 <section className="vt-panel vt-chart-panel"><div className="vt-panel-head"><div><h2>{symbol} Live Chart</h2><p>Deriv OHLC history + current tick stream</p></div><div className="vt-timeframes">{TIMEFRAMES.map(x=><button key={x.seconds} className={tf===x.seconds?"active":""} onClick={()=>setTf(x.seconds)}>{x.label}</button>)}</div></div><Chart candles={candles} price={price} symbol={symbol}/></section>
 <section className="vt-panel vt-tick-tape"><div className="vt-section-title"><div><h2>Live Tick Tape</h2><p>Real-time quotes for the selected market</p></div><span className="vt-ai-tag">{ticks.length} TICKS</span></div><div className="vt-tick-grid">{ticks.slice(0,20).map((t,i)=><div className="vt-tick-row" key={`${t.epoch}-${i}`}><span>{new Date(t.epoch*1000).toLocaleTimeString()}</span><strong>{fmt(t.quote,8)}</strong><small>{i===0?"LATEST":"TICK"}</small></div>)}</div>{!ticks.length&&<div className="vt-empty">Waiting for live ticks…</div>}</section>
 <div className="vt-lower-grid"><section className="vt-panel"><div className="vt-section-title"><div><h2>Real Order Ticket</h2><p>Deriv ACCU contract execution</p></div><span className="vt-ai-tag">REAL</span></div><label className="vt-label">Selected market<input value={symbol} readOnly/></label><div className="vt-order-price"><div><span>Live price</span><strong>{price?fmt(price,8):"Waiting…"}</strong></div><span className={feed==="LIVE"?"vt-feed live":"vt-feed"}>{feed}</span></div><div className="vt-risk-fields"><label className="vt-label">Stake<input type="number" min="0.01" step="0.01" value={stake} onChange={e=>setStake(e.target.value)}/></label><label className="vt-label">Growth %<input type="number" min="0.01" step="0.01" value={growth} onChange={e=>setGrowth(e.target.value)}/></label></div><div className="vt-order-actions"><button className="vt-buy" disabled={busy||!price} onClick={buy}>{busy?"PROCESSING…":"BUY REAL ACCU"}</button><button className="vt-sell" disabled={busy||!selectedContract} onClick={sell}>{busy?"PROCESSING…":"SELL SELECTED"}</button></div><small className="vt-gate-note">No browser Deriv token is exposed. The server performs the proposal, safety-gate check and authenticated order.</small></section>
 <section className="vt-panel"><div className="vt-section-title"><div><h2>Wallet ↔ Trading Account</h2><p>Actual Deriv wallet transfer rail</p></div><span className="vt-ai-tag">PAYMENT SCOPE</span></div><button className="vt-ai-button" onClick={loadWallets}>REFRESH DERIV WALLETS</button><div className="vt-data-list">{wallets.map(w=><div className="audit-row" key={w.wallet_id||w.type}><span>{w.type||"wallet"} · {w.currency||account?.currency||"USD"}</span><b>{w.balance??w.balances?.[account?.currency||"USD"]?.balance??"—"}</b></div>)}</div><label className="vt-label">Amount<input type="number" min="0.01" step="0.01" value={transferAmount} onChange={e=>setTransferAmount(e.target.value)} /></label><label className="vt-label">Direction<select value={transferDir} onChange={e=>setTransferDir(e.target.value)}><option value="to_wallet">Trading account → Deriv wallet</option><option value="from_wallet">Deriv wallet → trading account</option></select></label><button className="vt-ai-button" disabled={transferBusy||!transferAmount} onClick={transfer}>{transferBusy?"TRANSFERRING…":"CONFIRM REAL TRANSFER"}</button><p className="market-detail-note">Demo/sandbox funds are virtual and cannot be transferred into or out of a real Deriv wallet. This rail moves only real Deriv funds.</p></section></div>
 <section className="vt-panel"><div className="vt-section-title"><div><h2>Open Real Positions</h2><p>Live portfolio from the authenticated real account</p></div></div>{portfolio.length?<div className="vt-table-wrap"><table className="vt-table"><thead><tr><th>Contract</th><th>Market</th><th>Buy</th><th>Current</th><th>P/L</th><th>Action</th></tr></thead><tbody>{portfolio.map(p=><tr key={p.contract_id||p.id} onClick={()=>setSelectedContract(p)}><td>{p.contract_id||p.id}</td><td>{p.underlying_symbol||p.symbol||"—"}</td><td>{p.buy_price??"—"}</td><td>{p.bid_price??p.sell_price??"—"}</td><td className={Number(p.profit)>=0?"vt-positive":"vt-negative"}>{p.profit??"—"}</td><td><button className="vt-close" onClick={()=>setSelectedContract(p)}>Select</button></td></tr>)}</tbody></table></div>:<div className="vt-empty">No open real positions returned by Deriv.</div>}</section>
 {selectedContract&&<div className="vt-success">Selected contract <b>{selectedContract.contract_id}</b> on {selectedContract.underlying_symbol||selectedContract.symbol}. Press SELL SELECTED to close it at market.</div>}
 {msg&&<div className="vt-success">{msg}</div>}{error&&<div className="vt-error">{error}</div>}
 </main></div></div>;
}
