import { useEffect,useState } from "react";
import { sandboxEngine } from "../services/sandboxEngine";
import { useNavigate } from "react-router-dom";
export default function SandboxDashboard(){
 const [data,setData]=useState(null),[error,setError]=useState(""),navigate=useNavigate();const refresh=()=>sandboxEngine.snapshot().then(r=>setData(r.data)).catch(e=>setError(e.message));useEffect(()=>{refresh();const i=setInterval(refresh,10000);return()=>clearInterval(i)},[]);
 const a=data?.accounts?.[0],b=data?.balances?.[0];
 return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">ACCOUNTS / SANDBOX</span><h1>Sandbox Dashboard</h1><p>Isolated virtual capital and auditable trading state.</p></div><button className="primary-btn" onClick={()=>navigate("/app/trading/terminal")}>Open Trade Terminal</button></div>
 <div className="metric-grid"><div className="metric-card"><span>Initial capital</span><strong>{"$"}{Number(a?.initial_capital||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="metric-card"><span>Available</span><strong>{"$"}{Number(a?.available_capital||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="metric-card"><span>Withdrawable</span><strong>{"$"}{Number(a?.withdrawable||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="metric-card"><span>Equity</span><strong>{"$"}{Number(b?.equity||a?.available_capital||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div></div>
 {error&&<div className="error-box">{error}</div>}<div className="content-grid two-col"><section className="panel"><div className="panel-title"><h2>Positions</h2><span>{data?.positions?.length||0}</span></div>{!(data?.positions?.length)?<div className="empty-state">No open sandbox positions.</div>:data.positions.map(p=><div className="list-row" key={p.id}><div><strong>{p.symbol} · {p.side}</strong><small>Qty {p.quantity} · Entry {p.entry_price}</small></div><span className={Number(p.unrealized_pnl)>=0?"positive":"negative"}>{Number(p.unrealized_pnl).toFixed(2)}</span></div>)}</section>
 <section className="panel"><div className="panel-title"><h2>Immutable Ledger</h2><span>{data?.ledger?.length||0}</span></div>{!(data?.ledger?.length)?<div className="empty-state">Ledger is empty.</div>:data.ledger.slice(0,12).map(l=><div className="list-row" key={l.id}><div><strong>{l.entry_type}</strong><small>{new Date(l.created_at).toLocaleString()}</small></div><span>{l.direction} {"$"}{Number(l.amount).toFixed(2)}</span></div>)}</section></div></div>;
}