import { useEffect,useMemo,useState } from "react";
import { derivMarketService } from "../services/derivWebSocket";
import { sandboxEngine } from "../services/sandboxEngine";
import { useNavigate } from "react-router-dom";
export default function TradeTerminal(){
 const navigate=useNavigate(),[symbol,setSymbol]=useState("frxEURUSD"),[price,setPrice]=useState(null),[feed,setFeed]=useState("CONNECTING"),[quantity,setQuantity]=useState("0.10"),[sl,setSl]=useState(""),[tp,setTp]=useState(""),[account,setAccount]=useState(null),[positions,setPositions]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const refresh=async()=>{const r=await sandboxEngine.snapshot();setAccount(r.data?.accounts?.[0]||null);setPositions(r.data?.positions||[]);};
 useEffect(()=>{refresh().catch(e=>setError(e.message));const off=derivMarketService.onStatus(setFeed);derivMarketService.connect();const cb=t=>{const p=Number(t.quote);if(Number.isFinite(p)){setPrice(p);sandboxEngine.mark({symbol,price:p}).catch(()=>{});}};derivMarketService.subscribeTick(symbol,cb);return()=>off();},[symbol]);
 useEffect(()=>{const id=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(id)},[]);
 const displayPrice=useMemo(()=>price==null?"—":price.toFixed(5),[price]);
 const execute=async side=>{setError("");if(!account||price==null)return setError("Sandbox account or live price is unavailable.");setBusy(true);try{await sandboxEngine.executeOrder({account_id:account.id,symbol,side,quantity:Number(quantity),price,stop_loss:sl?Number(sl):null,take_profit:tp?Number(tp):null,idempotency_key:crypto.randomUUID()});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const close=async p=>{setError("");setBusy(true);try{await sandboxEngine.closePosition({position_id:p.id,exit_price:p.current_price,idempotency_key:crypto.randomUUID()});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">TRADING / SANDBOX</span><h1>Sandbox Trade Terminal</h1><p>Virtual execution only. Prices originate from the live Deriv public market feed; no external order is submitted.</p></div><button className="secondary-btn" onClick={()=>navigate("/app/sandbox/overview")}>Sandbox Overview</button></div>
 <div className="metric-grid"><div className="metric-card"><span>Sandbox balance</span><strong>{"$"}{Number(account?.available_capital||0).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><small>USD available capital</small></div><div className="metric-card"><span>Live price</span><strong>{displayPrice}</strong><small>{symbol} · {feed}</small></div><div className="metric-card"><span>Open positions</span><strong>{positions.length}</strong><small>Persisted in Supabase</small></div></div>
 <div className="content-grid two-col"><section className="panel"><div className="panel-title"><h2>Virtual Order Execution</h2><span className="status-pill">{feed}</span></div><label>Market<select value={symbol} onChange={e=>setSymbol(e.target.value)}><option value="frxEURUSD">EUR/USD</option><option value="frxGBPUSD">GBP/USD</option><option value="frxUSDJPY">USD/JPY</option></select></label><label>Size (lots)<input type="number" min="0.01" step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Stop Loss<input type="number" value={sl} onChange={e=>setSl(e.target.value)} placeholder="Optional"/></label><label>Take Profit<input type="number" value={tp} onChange={e=>setTp(e.target.value)} placeholder="Optional"/></label><div className="action-row"><button disabled={busy||price==null} className="primary-btn buy" onClick={()=>execute("BUY")}>BUY</button><button disabled={busy||price==null} className="primary-btn sell" onClick={()=>execute("SELL")}>SELL</button></div>{error&&<div className="error-box">{error}</div>}</section>
 <section className="panel"><div className="panel-title"><h2>Open Positions</h2><span>{positions.length}</span></div>{!positions.length?<div className="empty-state">No active virtual positions.</div>:positions.map(p=><div className="list-row" key={p.id}><div><strong>{p.symbol} · {p.side}</strong><small>Entry {Number(p.entry_price).toFixed(5)} · Current {Number(p.current_price).toFixed(5)}</small></div><div className={Number(p.unrealized_pnl)>=0?"positive":"negative"}>{Number(p.unrealized_pnl).toFixed(2)} <button className="secondary-btn" disabled={busy} onClick={()=>close(p)}>CLOSE</button></div></div>)}</section></div></div>;
}