import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../supabaseClient";
import LiveMarketPanel from "../components/LiveMarketPanel";
import { sandboxEngine } from "../services/sandboxEngine";

const SYMBOLS = [{ symbol: "frxEURUSD", name: "EUR/USD" }, { symbol: "frxGBPUSD", name: "GBP/USD" }, { symbol: "frxUSDJPY", name: "USD/JPY" }];
const fmt = (n, digits = 5) => Number.isFinite(Number(n)) ? Number(n).toLocaleString("en-US", { maximumFractionDigits: digits, minimumFractionDigits: Math.min(2, digits) }) : "—";

function CandleChart({ candles, symbol, price }) {
  const width = 900, height = 310, pad = 22, data = candles.slice(-36);
  if (data.length < 2) return <div className="vt-chart-empty"><span className="vt-live-dot" /> Waiting for live ticks to build candles for {symbol}. Historical candles will appear when a history feed is connected.</div>;
  const lo = Math.min(...data.map(c => c.low)), hi = Math.max(...data.map(c => c.high)), range = hi - lo || Math.max(Math.abs(hi) * .0001, .00001);
  const y = v => pad + ((hi - v) / range) * (height - pad * 2), step = (width - pad * 2) / data.length;
  return <svg className="vt-chart-svg" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Candlestick chart for ${symbol} based on received live ticks`}>
    {[0,1,2,3,4].map(i => <g key={i}><line x1={pad} x2={width-pad} y1={pad+i*(height-pad*2)/4} y2={pad+i*(height-pad*2)/4} stroke="currentColor" opacity=".13" strokeDasharray="4 5"/><text x={width-pad} y={pad+i*(height-pad*2)/4-4} textAnchor="end" fill="currentColor" opacity=".55" fontSize="11">{fmt(hi-i*range/4, 6)}</text></g>)}
    {data.map((c,i) => { const x=pad+i*step+step/2, up=c.close>=c.open, color=up?"#34d399":"#f87171", top=y(Math.max(c.open,c.close)), bottom=y(Math.min(c.open,c.close)); return <g key={c.time}><line x1={x} x2={x} y1={y(c.high)} y2={y(c.low)} stroke={color} strokeWidth="1.4"/><rect x={x-Math.max(2,step*.27)} y={top} width={Math.max(4,step*.54)} height={Math.max(1,bottom-top)} fill={color} rx="1"/></g>; })}
    {Number.isFinite(price) && price>=lo && price<=hi && <g><line x1={pad} x2={width-pad} y1={y(price)} y2={y(price)} stroke="#60a5fa" strokeDasharray="5 4"/><text x={pad+4} y={y(price)-5} fill="#60a5fa" fontSize="11">{fmt(price,6)}</text></g>}
  </svg>;
}

export default function TradingTerminal() {
  const [symbol,setSymbol]=useState("frxEURUSD"), [tick,setTick]=useState(null), [feed,setFeed]=useState("WAITING"), [candles,setCandles]=useState([]), [timeframe,setTimeframe]=useState("M5"), [account,setAccount]=useState(null), [positions,setPositions]=useState([]), [quantity,setQuantity]=useState("0.01"), [ai,setAi]=useState(null), [aiBusy,setAiBusy]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const latestCandleRef=useRef(null);
  const refresh=async()=>{const r=await sandboxEngine.snapshot();setAccount(r.data?.accounts?.[0]||null);setPositions(r.data?.positions||[]);};
  useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{setCandles([]);setTick(null);setAi(null);latestCandleRef.current=null;},[symbol,timeframe]);
  const onPrice=next=>{const price=Number(next?.quote);if(!Number.isFinite(price))return;setTick({price,epoch:Number(next.epoch),pipSize:next.pipSize});setFeed("LIVE");const interval=timeframe==="M1"?60:timeframe==="M5"?300:timeframe==="M15"?900:3600;const bucket=Math.floor(Number(next.epoch||Date.now()/1000)/interval)*interval;const prev=latestCandleRef.current;if(!prev||prev.time!==bucket){const candle={time:bucket,open:price,high:price,low:price,close:price};latestCandleRef.current=candle;setCandles(list=>[...list,candle].slice(-120));}else{const candle={...prev,high:Math.max(prev.high,price),low:Math.min(prev.low,price),close:price};latestCandleRef.current=candle;setCandles(list=>{const copy=[...list];if(copy.length)copy[copy.length-1]=candle;else copy.push(candle);return copy;});}sandboxEngine.mark({symbol,price}).catch(()=>{});};
  const symbolName=SYMBOLS.find(s=>s.symbol===symbol)?.name||symbol;
  const openPnl=useMemo(()=>positions.reduce((sum,p)=>sum+Number(p.unrealized_pnl||0),0),[positions]);
  const runAI=async()=>{if(!tick)return setError("Wait for a verified live price before requesting analysis.");setError("");setAiBusy(true);setAi(null);const recent=candles.slice(-12).map(c=>({open:c.open,high:c.high,low:c.low,close:c.close}));const prompt=`Provide a concise, risk-aware educational market review for ${symbol} on ${timeframe}. Current observed Deriv public-feed price: ${tick.price}. Recent locally collected OHLC candles: ${JSON.stringify(recent)}. State data limitations, describe observed momentum only if enough candles exist, mention volatility/uncertainty, and do not promise returns or give certainty. This is sandbox decision support, not an instruction to trade.`;try{const {data,error:invokeError}=await supabase.functions.invoke("ai-assistant",{body:{mode:"advisor",message:prompt,history:[]}});if(invokeError)throw new Error(data?.error||invokeError.message);if(!data?.ok||!data?.answer)throw new Error(data?.error||"AI service did not return an analysis.");setAi({text:data.answer,symbol,price:tick.price,at:Date.now()});}catch(e){setError("AI analysis unavailable: "+(e.message||"Please retry."));}finally{setAiBusy(false);}};
  const execute=async side=>{setError("");if(!ai||ai.symbol!==symbol||!tick||Date.now()-ai.at>120000)return setError("Run a fresh AI review for this market before placing a sandbox order.");if(!account)return setError("No authenticated sandbox account was found.");setBusy(true);try{await sandboxEngine.executeOrder({account_id:account.id,symbol,side,quantity:Number(quantity),price:tick.price,stop_loss:null,take_profit:null,idempotency_key:crypto.randomUUID()});await refresh();}catch(e){setError(e.message||"Sandbox order failed.");}finally{setBusy(false);}};
  const close=async p=>{if(!tick)return setError("Waiting for the current market price before closing.");setBusy(true);setError("");try{await sandboxEngine.closePosition({position_id:p.id,exit_price:tick.price,idempotency_key:crypto.randomUUID()});await refresh();}catch(e){setError(e.message||"Could not close position.");}finally{setBusy(false);}};
  return <div className="vt-page">
    <header className="vt-heading"><div><span className="eyebrow">VELTRION / SANDBOX</span><h1>Trading Terminal</h1><p>Market watch, tick-built candlesticks, sandbox positions and AI review.</p></div><span className={feed==="LIVE"?"vt-feed live":"vt-feed"}><i/> {feed==="LIVE"?"LIVE MARKET DATA":feed}</span></header>
    <div className="vt-metrics"><div className="vt-metric"><span>Sandbox balance</span><strong>${fmt(account?.available_capital,2)}</strong><small>Available virtual capital</small></div><div className="vt-metric"><span>Selected price</span><strong>{tick?fmt(tick.price,8):"—"}</strong><small>{symbolName} · public feed</small></div><div className="vt-metric"><span>Open positions</span><strong>{positions.length}</strong><small>Supabase sandbox records</small></div><div className="vt-metric"><span>Floating P/L</span><strong className={openPnl>=0?"vt-positive":"vt-negative"}>${fmt(openPnl,2)}</strong><small>Reported by sandbox service</small></div></div>
    <LiveMarketPanel compact selectedSymbol={symbol} onSymbolChange={setSymbol} onPriceChange={onPrice}/>
    <section className="vt-panel"><div className="vt-panel-head"><div><h2>{symbolName} <span className="vt-symbol-code">{symbol}</span></h2><p>Tick-built candles · current session only</p></div><div className="vt-timeframes">{["M1","M5","M15","H1"].map(t=><button key={t} className={timeframe===t?"active":""} onClick={()=>setTimeframe(t)}>{t}</button>)}</div></div><CandleChart candles={candles} symbol={symbolName} price={tick?.price}/><div className="vt-chart-note">Candles are built from actual received ticks while this screen is open. Historical candles are not yet loaded; gaps or delayed ticks may affect the display.</div></section>
    <div className="vt-lower-grid"><section className="vt-panel"><div className="vt-section-title"><div><h2>AI Market Review</h2><p>Required before placing sandbox orders</p></div><span className="vt-ai-tag">ADVISORY</span></div><button className="vt-ai-button" onClick={runAI} disabled={aiBusy||!tick}>{aiBusy?"ANALYZING MARKET…":"ANALYZE SELECTED MARKET"}</button>{ai&&ai.symbol===symbol&&<div className="vt-ai-result"><div className="vt-ai-meta">Reviewed {new Date(ai.at).toLocaleTimeString()} · price {fmt(ai.price,8)}</div><p>{ai.text}</p></div>}<div className="vt-disclaimer">AI output is informational, can be wrong, and does not guarantee results. It never executes trades.</div></section>
    <section className="vt-panel"><div className="vt-section-title"><div><h2>Sandbox Order Ticket</h2><p>Virtual execution only · no broker order is sent</p></div></div><label className="vt-label">Market<select value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOLS.map(s=><option key={s.symbol} value={s.symbol}>{s.name} ({s.symbol})</option>)}</select></label><label className="vt-label">Position size (lots)<input type="number" min="0.01" step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><div className="vt-price-row"><span>Current observed price</span><strong>{tick?fmt(tick.price,8):"Waiting for feed…"}</strong></div><div className="vt-order-actions"><button className="vt-buy" disabled={busy||!tick||!ai||ai.symbol!==symbol||Date.now()-ai.at>120000} onClick={()=>execute("BUY")}>BUY</button><button className="vt-sell" disabled={busy||!tick||!ai||ai.symbol!==symbol||Date.now()-ai.at>120000} onClick={()=>execute("SELL")}>SELL</button></div><small className="vt-gate-note">{ai&&ai.symbol===symbol?"AI review available; order requires your explicit confirmation tap.":"Run AI analysis first to unlock sandbox order controls."}</small></section></div>
    <section className="vt-panel"><div className="vt-section-title"><div><h2>Open Positions</h2><p>Automatically refreshed from the sandbox service</p></div><strong>{positions.length}</strong></div>{!positions.length?<div className="vt-empty">No open sandbox positions.</div>:<div className="vt-table-wrap"><table className="vt-table"><thead><tr><th>Market</th><th>Side</th><th>Quantity</th><th>Entry</th><th>Current</th><th>Unrealized P/L</th><th>Action</th></tr></thead><tbody>{positions.map(p=><tr key={p.id}><td>{p.symbol}</td><td className={String(p.side).toUpperCase()==="BUY"?"vt-positive":"vt-negative"}>{p.side}</td><td>{p.quantity}</td><td>{fmt(Number(p.entry_price),8)}</td><td>{fmt(Number(p.current_price),8)}</td><td className={Number(p.unrealized_pnl)>=0?"vt-positive":"vt-negative"}>{fmt(Number(p.unrealized_pnl),2)}</td><td><button className="vt-close" disabled={busy||!tick} onClick={()=>close(p)}>Close</button></td></tr>)}</tbody></table></div>}</section>
    {error&&<div className="vt-error" role="alert">{error}</div>}
  </div>;
}
